name: Build and Push Docker Image

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and Push
        run: |
          IMAGE=ghcr.io/${{ github.actor }}/${{ github.repository }}:${GITHUB_REF##*/}
          docker build -t $IMAGE -f Dockerfile .
          docker push $IMAGE
